GET http://localhost:3000

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "tendangnhap": "test1",
  "matkhau": "123"
}

###
GET http://localhost:3000/user/liked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5kYW5nbmhhcCI6InRlc3QxIiwibWF0a2hhdSI6IjEyMyIsImlhdCI6MTcwMjk3ODIzNSwiZXhwIjoxNzAyOTg1NDM1fQ.HSt0R-D1v-JAXjWVBaiOaeIlCrd5ipfIoPN6Zg0liOM