GET http://localhost:3000

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "tendangnhap": "test1",
  "matkhau": "123"
}

###
GET http://localhost:3000/user/liked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIwMSwiVGVuIjoiVGhhbmggTmd1eWVuIiwiRW1haWwiOm51bGwsIlRlbkRhbmdOaGFwIjoidGVzdDEiLCJNYXRLaGF1IjoiMTIzIiwiQW5oIjoiL3VzZXIvdXNlci5wbmciLCJpYXQiOjE3MDMyNDA5MjMsImV4cCI6MTcwMzI0ODEyM30.XNUdYEBckduBl9pAcE0avzU8Me_Md0fYaSHh4n97cmo
###

GET http://localhost:3000/user/check_like/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5kYW5nbmhhcCI6InRlc3QxIiwibWF0a2hhdSI6IjEyMyIsImlhdCI6MTcwMzI0MDUyMiwiZXhwIjoxNzAzMjQ3NzIyfQ.2awS_STBrz_IlK07yJ6rQbHbgjr4Fz3bCYvSd2ODNXs





