GET http://localhost:3000

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "hoten": "nguyen thanh",
  "tendangnhap": "test1",
  "matkhau": "123"
}

POST http://localhost:3000/login
Content-Type: application/json

{
  "tendangnhap": "test1",
  "matkhau": "123"
}


###
GET http://localhost:3000/user/liked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIwMSwiVGVuIjoiVGhhbmggTmd1eWVuIiwiRW1haWwiOm51bGwsIlRlbkRhbmdOaGFwIjoidGVzdDEiLCJNYXRLaGF1IjoiMTIzIiwiQW5oIjoiL3VzZXIvdXNlci5wbmciLCJpYXQiOjE3MDMzMTgzMzEsImV4cCI6MTcwMzMyNTUzMX0.82dFnPtZuOEGcrqdUgXmNJbkXqQmjxyTt_QLJ7B9Jxw

###

GET http://localhost:3000/user/check_like/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIwMSwiVGVuIjoiVGhhbmggTmd1eWVuIiwiRW1haWwiOm51bGwsIlRlbkRhbmdOaGFwIjoidGVzdDEiLCJNYXRLaGF1IjoiMTIzIiwiQW5oIjoiL3VzZXIvdXNlci5wbmciLCJpYXQiOjE3MDMzMTgzMzEsImV4cCI6MTcwMzMyNTUzMX0.82dFnPtZuOEGcrqdUgXmNJbkXqQmjxyTt_QLJ7B9Jxw


###
POST http://localhost:3000/user/like/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIwMSwiVGVuIjoiVGhhbmggTmd1eWVuIiwiRW1haWwiOm51bGwsIlRlbkRhbmdOaGFwIjoidGVzdDEiLCJNYXRLaGF1IjoiMTIzIiwiQW5oIjoiL3VzZXIvdXNlci5wbmciLCJpYXQiOjE3MDMzMTgzMzEsImV4cCI6MTcwMzMyNTUzMX0.82dFnPtZuOEGcrqdUgXmNJbkXqQmjxyTt_QLJ7B9Jxw

###

DELETE  http://localhost:3000/user/unlike/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIwMSwiVGVuIjoiVGhhbmggTmd1eWVuIiwiRW1haWwiOm51bGwsIlRlbkRhbmdOaGFwIjoidGVzdDEiLCJNYXRLaGF1IjoiMTIzIiwiQW5oIjoiL3VzZXIvdXNlci5wbmciLCJpYXQiOjE3MDMzMTgzMzEsImV4cCI6MTcwMzMyNTUzMX0.82dFnPtZuOEGcrqdUgXmNJbkXqQmjxyTt_QLJ7B9Jxw

### 







